### ISSUE TITLE
Incorrect document paths

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/Cofoundry.Plugins.Azure#2]
Hi, 
I don't know if this issue is for this project or for Cofoundry project because is related to both.

When the plugin is installed, documents are saved automatically in Azure Storage, but in their details ("Admin/Documents/id) it is showed with an incorrect path, it shows "assets/documents/...".
![image](https://user-images.githubusercontent.com/8802992/51316758-e818ea00-1a55-11e9-9f3a-9b1c24e82a3e.png)
I think that Cofoundry should detect the plugin and set the path to Azure resource or similar. 

Thanks

**Comment by HeyJoel** [comment]
For image assets this is because the image requests are run through Cofoundry to support dynamic image resizing. If we linked directly to the file we would not be able to support that.

Documents follows the same model, the main benefit for documents is that permissions can be locked down by user role, and in the future we could support more granular permissions to individual documents via the CMS or even a publish workflow for documents. Again, if we linked directly to the file we would not be able to support that.

Having said that I can see that in some situations it might be advantageous to link directly to the blob file to improve performance so we could look into that as an option. Typically we use a reverse proxy CDN like cloudflare in front of our production websites to cache static files so it wouldn't make much of a difference.
